services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-postgres}
      - POSTGRES_DB=${PG_DB:-cloud}
    networks:
      - backend
    healthcheck:
      test: [CMD-SHELL, "su -c 'pg_isready -U postgres' postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5433:5432"

  postgres-migrate:
    image: migrate/migrate:4
    volumes:
      - ../migrations:/migrations
    networks:
      - backend

  kafka:
    image: apache/kafka:4.1.2
    restart: unless-stopped
    hostname: kafka
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      - CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    networks:
      - backend
    ports:
      - "29092:29092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui
    ports:
      - "9080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - backend

  prometheus:
    image: prom/prometheus:v3
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend

  api:
    build:
      context: ..
      dockerfile: deploy/docker/api.Dockerfile
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      HTTP_ADDR: :8080
      API_METRICS_ADDR: :8081
      FILE_STORAGE_DIR: ./storage
      LOGGER_FOLDER: ./logs
      PG_HOST: postgres
      PG_PORT: "5432"
      KAFKA_BROKERS: kafka:9092
    ports:
      - "8080:8080"
    volumes:
      - api-logs:/app/logs
      - file-storage:/app/storage
    restart: unless-stopped
    networks:
      - backend

  worker:
    build:
      context: ..
      dockerfile: deploy/docker/worker.Dockerfile
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      WORKER_METRICS_ADDR: :8081
      FILE_STORAGE_DIR: ./storage
      LOGGER_FOLDER: ./logs
      PG_HOST: postgres
      PG_PORT: "5432"
      KAFKA_BROKERS: kafka:9092
    volumes:
      - worker-logs:/app/logs
      - file-storage:/app/storage
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:

volumes:
  api-logs:
  worker-logs:
  file-storage:

  postgres-data:
  kafka-data:
