global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "cloud-backend-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "api:8081"

  - job_name: "cloud-backend-worker"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "worker:8081"
